require_relative './nodes/base_node'
require_relative './nodes/term_node'
require_relative './nodes/root_node'
require_relative './nodes/and_node'
require_relative './nodes/or_node'

require_relative './nodes/equality_node'
require_relative './nodes/boolean_equality_node'
require_relative './nodes/exists_node'
require_relative './nodes/greater_than_node'
require_relative './nodes/less_than_node'
