require_relative './nodes/base_node'
require_relative './nodes/term_node'
require_relative './nodes/root_node'
require_relative './nodes/and_node'
require_relative './nodes/or_node'

require_relative './nodes/equality_node'
require_relative './nodes/boolean_equality_node'
require_relative './nodes/exists_node'
require_relative './nodes/includes'

require_relative './nodes/greater_than_node'
require_relative './nodes/date_attr/greater_than_node'
require_relative './nodes/datetime_attr/greater_than_node'
require_relative './nodes/number_attr/greater_than_node'

require_relative './nodes/less_than_node'
require_relative './nodes/date_attr/less_than_node'
require_relative './nodes/datetime_attr/less_than_node'
require_relative './nodes/number_attr/less_than_node'
